webapp/config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do


  resources :marquees

  mount Sidekiq::Web => '/sidekiq'

  resources :users
  resources :contents
  resources :documents
  resources :images
  resources :groups
  resources :schedules do 
    resources :deployments, only: [:index]
    resources :content_schedules
    resources :attachments
  end

  post 'schedules/:schedule_id/attachments/:id/up_play_order' => 'attachments#up_play_order', :as => :attachment_up_play_order
  post 'schedules/:schedule_id/attachments/:id/down_play_order' => 'attachments#down_play_order', :as => :attachment_down_play_order

  post 'schedules/:schedule_id/content_schedules/:id/up_play_order' => 'content_schedules#up_play_order', :as => :content_schedule_up_play_order
  post 'schedules/:schedule_id/content_schedules/:id/down_play_order' => 'content_schedules#down_play_order', :as => :content_schedule_down_play_order

  post 'schedules/:id/deploy' => 'schedules#deploy', :as => :deploy_schedule
  post 'marquees/:id/push' => 'marquees#push', :as => :push_marquee


  get 'dashboard/clients', :as => :clients_status
  get 'dashboard/schedules', :as => :schedules_status

  get 'sessions/new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  resources :users
  resources :clients


  # You can have the root of your site routed with "root"
  root 'dashboard#clients'

end

webapp/app/models/marquee.rb
class Marquee < ActiveRecord::Base

  after_update :reinitialize_pushes

  has_many :pushes, :dependent => :delete_all
  has_many :clients, :through => :pushes

  enum :priority => [:low, :medium, :high]

  HOURS = ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11",
           "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"]

  MINUTES = [ "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11",
              "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23",
              "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", 
              "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", 
              "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"]


  DAYS_OF_WEEK_COLUMNS = ['is_shown_on_monday', 
                          'is_shown_on_tuesday', 
                          'is_shown_on_wednesday', 
                          'is_shown_on_thursday', 
                          'is_shown_on_friday', 
                          'is_shown_on_saturday', 
                          'is_shown_on_sunday']

  DAYS_OF_WEEK = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']

  # Validations
  validates_presence_of :start_hour
  validates_presence_of :start_minute
  validates_presence_of :end_hour
  validates_presence_of :end_minute
  validates_presence_of :start_date
  validates_presence_of :end_date
  validates_presence_of :content

  validates_inclusion_of :start_hour, :in => Marquee::HOURS
  validates_inclusion_of :start_minute, :in => Marquee::MINUTES
  validates_inclusion_of :end_hour, :in => Marquee::HOURS
  validates_inclusion_of :end_minute, :in => Marquee::MINUTES

  def get_start_time
    self.start_hour + ":" + self.start_minute + ":00"
  end

  def get_end_time
    self.end_hour + ":" + self.end_minute + ":00"
  end

  def get_start_date_time
    self.start_date.to_s + " " + self.get_start_time
  end

  def get_end_date_time
    self.end_date.to_s + " " + self.get_end_time
  end

  def get_days_of_the_week
    # self is not a class/module (cannot send)
    flags = DAYS_OF_WEEK_COLUMNS.collect { |day| self.method(day.to_sym).call() }
    results = []
    flags.each_with_index do |val, index|
      if val
        results << DAYS_OF_WEEK[index]
      end
    end
    results
  end

  def get_json_object(action = "add")
    return {
      "text" => self.content,
      "action" => action,
      "start_datetime" => self.get_start_date_time,
      "end_datetime" => self.get_end_date_time,
      "days_of_week" => self.get_days_of_the_week
      }.to_json
  end

  def push!
    self.pushes.each do |push|
      PushJob.perform_later(push[:id])
    end
  end


private
    def reinitialize_pushes
    self.pushes.each do |push|
      push.not_started!
    end
  end


end

webapp/app/controllers/marquees_controller.rb
class MarqueesController < ApplicationController
  before_action :set_marquee, only: [:show, :edit, :update, :destroy, :push]

  # GET /marquees
  # GET /marquees.json
  def index
    @marquees = Marquee.all
  end

  # GET /marquees/1
  # GET /marquees/1.json
  def show
    @clients = @marquee.clients
    @pushes = @marquee.pushes
  end

  # GET /marquees/new
  def new
    @marquee = Marquee.new
    @marquee.start_date = Date.today
    @marquee.end_date = Date.today
    @marquee.start_hour = Time.now.hour
    @marquee.end_hour = Time.now.hour

    @marquee.clients = []
    @clients = []
  end

  # GET /marquees/1/edit
  def edit
    @clients = @marquee.clients
    @pushes = @marquee.pushes
  end

  def push
    @marquee.push!
    @marquee.update_attributes(:is_synced => true)
    redirect_to @marquee, notice: "Push process started"
  end

  # POST /marquees
  # POST /marquees.json
  def create
    @marquee = Marquee.new(marquee_params)
    @clients = Client.all.select {|c| marquee_params[:client_ids].include? c }

    respond_to do |format|
      if @marquee.save
        format.html { redirect_to @marquee, notice: 'Marquee was successfully created.' }
        format.json { render :show, status: :created, location: @marquee }
      else
        format.html { render :new }
        format.json { render json: @marquee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marquees/1
  # PATCH/PUT /marquees/1.json
  def update
    respond_to do |format|
      if @marquee.update(marquee_params) && @marquee.update_attributes(:is_synced => false)
        format.html { redirect_to @marquee, notice: 'Marquee was successfully updated.' }
        format.json { render :show, status: :ok, location: @marquee }
      else
        format.html { render :edit }
        format.json { render json: @marquee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marquees/1
  # DELETE /marquees/1.json
  def destroy
  
    @pushes = @marquee.pushes
    @pushes.each do |push|
      push.update_attributes(:retries_count => 0)
      DestroyPushJob.perform_later(push.id)
    end

    respond_to do |format|
      format.html { redirect_to marquees_url, notice: 'Marquee Stop has been iniated successfully, it will take some time to complete.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marquee
      @marquee = Marquee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marquee_params
      params.require(:marquee).permit(:content,
                                      :priority,
                                      :start_hour,
                                      :start_minute,
                                      :end_hour,
                                      :end_minute,
                                      :start_date,
                                      :end_date,
                                      {:client_ids => []},
                                      {:group_ids => []})

    end
end

webapp/app/helpers/marquees_helper.rb
module MarqueesHelper
end

webapp/app/views/marquees/_form.html.erb
<div class="row">
  <%= simple_form_for(@marquee) do |f| %>
    <%= f.error_notification %>
    <% if @marquee.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @marquee.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-inputs">
      <div class="col-md-12">
        <div class="col-md-10">
          <label for="marquee_priority" class="col-md-2 control-label">Priority</label>
          <%= f.input :priority, :as => :select, :collection => Marquee.priorities.keys.to_a, :label => false %>
          <div class="row">
            <div class="form-group">
              <div class="col-md-12">
                  <div class="form-group row">
                    <label for="inputKey" class="col-md-2 control-label">Start Time</label>
                    <div class="col-md-4">
                        <%= f.date_select :start_date, :start_year => 2015, prompt: true, label: false, wrapper: false %>
                    </div>
                    <label for="inputValue" class="col-md-2 control-label">End Time</label>
                    <div class="col-md-4">
                        <%= f.date_select :end_date, :start_year => 2015, prompt: true, label: false, wrapper: false %>
                    </div>
                  </div>

                <div class="form-group row">
                  <label for="inputKey" class="col-md-2 control-label">Start Time (day)</label>
                  <div class="col-md-4">
                    <%= f.collection_select :start_hour, Marquee::HOURS, :to_s, :humanize %> : 
                    <%= f.collection_select :start_minute, Marquee::MINUTES, :to_s, :humanize %>
                  </div>
                  <label for="inputValue" class="col-md-2 control-label">End Time (day)</label>
                  <div class="col-md-4">
                    <%= f.collection_select :end_hour, Marquee::HOURS, :to_s, :humanize %> : 
                    <%= f.collection_select :end_minute, Marquee::MINUTES, :to_s, :humanize %>
                  </div>
                </div>


              </div>
            </div>
          </div>
          <%= f.input :content, :wrapper => :horizontal_input, :input_html => { :rows => "9" } %>
        </div>
      </div>


      <div class="row">
        <br />
        <br />
        <h6>Push to</h6>
        <div id="clients_table">

          <div class="field">
            <p><strong>Clients</strong></p>
            <%= hidden_field_tag("marquee[client_ids][]", nil) %>
            <table class="table table-condensed">
              <tr>
                <th></th>
                <th>IP Address </th>
                <th>Name </th>
                <th>Department </th>
                <th>Building </th>
                <th>Floor </th>
              </tr>
              <% Client.all.each do |client| %>
              <% id = client.id %>
              <tr>
                <td><%= check_box_tag("marquee[client_ids][]", id, id.in?(@clients.collect(&:id))) %></td> 
                <td><%= client[:ip_address] %></td>
                <td><%= client[:name] %></td>
                <td><%= client[:department] %></td>
                <td><%= client[:building] %></td>
                <td><%= client[:floor] %></td>

              </tr>
              <% end %>
            </table>
          </div>

        </div>
      </div>



    </div>
    <br />
    <div class="form-actions">
      <%= f.button :submit, :class => "btn btn-large btn-primary" %>
    </div>
  <% end %>
</div>

webapp/app/views/marquees/edit.html.erb
<h4>Editing</h4>

<br />

<div class="row">
  <div class="col-md-11">
    <%= render 'form' %>
  </div>
</div>

webapp/app/views/marquees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Marquees</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Content</th>
      <th># of Clients</th>
      <th>Synced with clients? </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marquees.each do |marquee| %>
      <tr>
        <td><%= marquee.content %></td>
        <td><%= marquee.pushes.count %></td>
        <td><%= marquee.is_synced %>
        <td><%= link_to 'Show', marquee, class: "btn btn-mini btn-primary" %></td>
        <td><%= link_to 'Edit', edit_marquee_path(marquee), class: "btn btn-mini btn-primary" %></td>
        <% if marquee.is_synced? %>
          <td><%= link_to 'Stop', marquee, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marquee', new_marquee_path, :class => "btn btn-primary" %>

webapp/app/views/marquees/new.html.erb
<h4>New Notice</h4>

<br />

<%= render 'form' %>

<%= link_to 'Back', marquees_path %>

webapp/app/views/marquees/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <div class="col-md-9">
    <% if @marquee.is_synced? %>
      <strong>The marquee is not synced with the clients. To sync, click push</strong>
      <br />
      <br />
    <% end %>

    <ul>
      <li>
        <strong>Start Date : </strong><%= @marquee.start_date %>
      </li>
      <li>
        <strong>End Date : </strong><%= @marquee.end_date %>
      </li>
      <li>
        <strong> Daily start time : </strong><%= @marquee.get_start_time %>
      </li>
      <li>
        <strong> Daily end time : </strong><%= @marquee.get_end_time %>
      </li>
      <li><strong>Content : </strong><%= @marquee.content %></li>
      <li><strong>Priority : </strong><%= @marquee.priority %></li>
    </ul>

  </div>
  <div class="col-md-3">
    <%= link_to "Edit Notice", edit_marquee_path(@marquee), class: "btn btn-primary btn-block" %>
    <br />
    <%= button_to "Push Notice", push_marquee_path(@marquee), class: "btn btn-primary btn-block" %>
  </div>

</div>

<br />
<h6>Pushes </h6>
<%= render 'pushes/list' %>