webapp/config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do


  resources :marquees

  mount Sidekiq::Web => '/sidekiq'

  resources :users
  resources :contents
  resources :documents
  resources :images
  resources :groups
  resources :schedules do 
    resources :deployments, only: [:index]
    resources :content_schedules
    resources :attachments
  end

  post 'schedules/:schedule_id/attachments/:id/up_play_order' => 'attachments#up_play_order', :as => :attachment_up_play_order
  post 'schedules/:schedule_id/attachments/:id/down_play_order' => 'attachments#down_play_order', :as => :attachment_down_play_order

  post 'schedules/:schedule_id/content_schedules/:id/up_play_order' => 'content_schedules#up_play_order', :as => :content_schedule_up_play_order
  post 'schedules/:schedule_id/content_schedules/:id/down_play_order' => 'content_schedules#down_play_order', :as => :content_schedule_down_play_order

  post 'schedules/:id/deploy' => 'schedules#deploy', :as => :deploy_schedule
  post 'marquees/:id/push' => 'marquees#push', :as => :push_marquee


  get 'dashboard/clients', :as => :clients_status
  get 'dashboard/schedules', :as => :schedules_status

  get 'sessions/new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  resources :users
  resources :clients


  # You can have the root of your site routed with "root"
  root 'dashboard#clients'

end

webapp/app/models/schedule.rb
class Schedule < ActiveRecord::Base

  after_update :reinitialize_deployments
  after_update :update_action_column

  has_many :content_schedules, :dependent => :delete_all
  has_many :contents, :through => :content_schedules

  has_many :attachments, :dependent => :delete_all
  has_many :documents, :through => :attachments

  #has_and_belongs_to_many :clients
  has_many :deployments, :dependent => :delete_all
  has_many :clients, :through => :deployments

  # TODO: have to take care of groups
  #has_and_belongs_to_many :groups

  accepts_nested_attributes_for :content_schedules, allow_destroy: true, :reject_if => lambda { |c| c[:play_order].blank? }

  enum :priority => [:low, :medium, :high]

  HOURS = ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11",
           "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"]

  MINUTES = [ "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11",
              "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23",
              "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", 
              "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", 
              "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"]


  DAYS_OF_WEEK_COLUMNS = ['is_played_on_monday', 
                          'is_played_on_tuesday', 
                          'is_played_on_wednesday', 
                          'is_played_on_thursday', 
                          'is_played_on_friday', 
                          'is_played_on_saturday', 
                          'is_played_on_sunday']

  DAYS_OF_WEEK = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']

  # Validations
  validates_presence_of :start_hour
  validates_presence_of :start_minute
  validates_presence_of :end_hour
  validates_presence_of :end_minute
  validates_presence_of :start_date
  validates_presence_of :end_date
  validates_presence_of :priority
  validates_presence_of :description
  validates_presence_of :name

  validates_inclusion_of :start_hour, :in => Schedule::HOURS
  validates_inclusion_of :start_minute, :in => Schedule::MINUTES
  validates_inclusion_of :end_hour, :in => Schedule::HOURS
  validates_inclusion_of :end_minute, :in => Schedule::MINUTES

  # validates_inclusion_of :is_played_on_monday, :in => [0,1]
  # validates_inclusion_of :is_played_on_tuesday, :in => [0,1]
  # validates_inclusion_of :is_played_on_wednesday, :in => [0,1]
  # validates_inclusion_of :is_played_on_thursday, :in => [0,1]
  # validates_inclusion_of :is_played_on_friday, :in => [0,1]
  # validates_inclusion_of :is_played_on_saturday, :in => [0,1]
  # validates_inclusion_of :is_played_on_sunday, :in => [0,1]


  def get_start_time
    self.start_hour + ":" + self.start_minute + ":00"
  end

  def get_end_time
    self.end_hour + ":" + self.end_minute + ":00"
  end

  def get_start_date_time
    self.start_date.to_s + " " + self.get_start_time
  end

  def get_end_date_time
    self.end_date.to_s + " " + self.get_end_time
  end

  def get_days_of_the_week
    # self is not a class/module (cannot send)
    flags = DAYS_OF_WEEK_COLUMNS.collect { |day| self.method(day.to_sym).call() }
    results = []
    flags.each_with_index do |val, index|
      if val
        results << DAYS_OF_WEEK[index]
      end
    end
    results
  end

  def get_all_contents_and_attachments
    everything = self.attachments + self.content_schedules
    everything.sort_by(&:play_order)
  end

  def get_max_play_order
    all_files = self.get_all_contents_and_attachments
    if all_files.any?
      all_files.map(&:play_order).max
    else
      0
    end
  end

  def rearrange_play_order!
    atts = self.attachments.sort_by(&:play_order)
    cons = self.content_schedules.sort_by(&:play_order)

    if atts.empty? and cons.empty?
      return
    end

    all_files = []

    if atts.any? and atts[0].play_order == 1
      all_files = atts + cons
    else
      all_files = cons + atts
    end

    all_files.each_with_index do |obj, index|
      obj.update_attributes(:play_order => index+1)
      obj.save!
    end

  end

  # Give the union of this schedule's clients and this schedule's groups' clients
  def all_clients
    self.clients
  	#clients | groups.map(&:clients).flatten
  end

  def is_deployable
    flag = true
    self.attachments.each do |att|
      if not att.is_converted
        flag = false
      end
    end

    self.content_schedules.each do |cs|
      if not cs.is_converted
        flag = false
      end
    end
    flag and (not self.delete_flag)
  end

  def deploy!
    flag = self.is_deployable()

    if flag
      self.deployments.each do |deployment|
        deployment.update_attributes(:retries_count => 0)
        DeploymentJob.perform_later(deployment[:id])
      end
    end

    return flag
  end

  def get_json_object(action = "add")
    prioritized = {}
    min = 1
    max = 1

    content_files = []
    self.content_schedules.each do |cs|
      content = cs.content
      prioritized[cs[:play_order]] = {
        :type => :content,
        :obj => cs
      }
    end

    document_files = []
    self.attachments.each do |a|
      doc = a.document
      prioritized[a[:play_order]] = {
        :type => :document,
        :obj => a
      }
    end

    all_contents = []

    current_play_order = 1
    prioritized.keys.sort.each do |i| 
      elm = prioritized[i]

      if elm[:type] == :document
        attachment = elm[:obj]
        doc = attachment.document
        images = doc.images.sort_by { |x| x.get_converted_file_path(attachment.slide_interval_time) }
        images.each do |i|
          old_path = i.get_converted_file_path(attachment.slide_interval_time)
          new_path = Checksum.get_checksum_file_path!(old_path)
          all_contents << {
            "filename" => new_path.split('/').last,
            "type" => "VIDEO",                   # PDF are always JPG
            "path" => new_path,
            "play_order" => current_play_order,
            "interval" => attachment["slide_interval_time"]
          }

          current_play_order += 1
        end
      else
        # Content file (image/video)
        cs = elm[:obj]
        content = cs.content

        if type_map(content.content_type) == "VIDEO"
          old_path = Rails.root.join('public', content.file.file.file).to_s
          new_path = Checksum.get_checksum_file_path!(old_path)
          all_contents << {
            "filename" => new_path.split("/").last,
            "type" => type_map(content.content_type),
            "path" => new_path,
            "play_order" => cs[:play_order],
            "interval" => cs[:slide_interval_time]
          }
        else
          old_path = cs.get_converted_file_path(cs.slide_interval_time)
          new_path = Checksum.get_checksum_file_path!(old_path)
          all_contents << {
            "filename" => new_path.split("/").last,
            "type" => "VIDEO",               # converting IMAGES to VIDEO
            "path" => new_path,
            "play_order" => cs[:play_order],
            "interval" => cs[:slide_interval_time]
          }
        end

        current_play_order += 1

      end
    end

    return {
      "schedule_id" => self.id,
      "schedule_name" => self.name ? self.name : "",
      "schedule_desc" => self.description,
      "priority" => Schedule.priorities[self.priority],
      "action" => action,
      "start_datetime" => self.get_start_date_time,
      "end_datetime" => self.get_end_date_time,
      "days_of_week" => self.get_days_of_the_week,
      "marquee_text" => self.marquee,
      "content_files" => all_contents
    }.to_json
  end



  protected

  def reinitialize_deployments
    self.deployments.each do |deployment|
      deployment.not_started!
    end
  end

  def update_action_column
    self.action = "update"
  end

  def type_map(content_type)
    if content_type
      if content_type.starts_with?("video")
        "VIDEO"
      elsif content_type.starts_with?("image")
        "IMAGE"
      elsif content_type.starts_with?("application/pdf")
        "PDF"
      end
    else
      "UKNOWN"
    end
  end

end

webapp/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_filter :authenticate
  
  MAX_SCHEDULE_PER_PAGE = 50

  def index
  	#@schedules = Schedule.all.limit(10)
  	#@schedules = Schedule.find(:all, :order => "created_at DESC", :limit => MAX_SCHEDULE_PER_PAGE)
    @schedules = Schedule.order("created_at DESC").all()
  end

  def new
  	@schedule = Schedule.new
    @schedule.start_hour = "08"
    @schedule.end_hour = "20"


    @schedule.start_date = Date.today
    @schedule.end_date = Date.today
    @schedule.start_hour = Time.now.hour
    @schedule.end_hour = Time.now.hour
    

    @schedule.is_played_on_monday = true
    @schedule.is_played_on_tuesday = true
    @schedule.is_played_on_wednesday = true
    @schedule.is_played_on_thursday = true
    @schedule.is_played_on_friday = true
  end

  def create
    @schedule = Schedule.new(schedule_params)
    
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to edit_schedule_path(@schedule), notice: 'Schedule was successfully created.' }
        format.js { render js: %(window.location.href='#{edit_schedule_path(@schedule)}') }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  	@schedule = Schedule.find_by_id(params[:id])
    @attachments = @schedule.attachments.sort_by(&:play_order) if @schedule
    @documents = @schedule.documents if @schedule

    @everything = @schedule.get_all_contents_and_attachments if @schedule

    @deployments = @schedule.deployments if @schedule
    @clients = @schedule.clients
    @content_schedules = @schedule.content_schedules.sort_by(&:play_order) if @schedule
    @contents = @schedule.contents if @schedule
  end

  def update
  	@schedule = Schedule.find(params[:id])
  	respond_to do |format|
      if @schedule.update(schedule_params)
        @schedule.update_attributes(:delete_flag => false)
        @clients = @schedule.clients
        flag = true
        unless params[:schedule][:documents].nil?
          params[:schedule][:documents].each { |doc, value|
            if value["enabled"]
              attachment = Attachment.find_or_initialize_by(:document_id => doc.to_i,
                                                            :schedule_id => @schedule.id)
              
              if value["slide_interval_time"].nil? or !value["slide_interval_time"].match(/^[0-9]+$/)
                flag = false
              end

              if value["play_order"].nil? or !value["play_order"].match(/^[0-9]+$/)
                flag = false
              end

              attachment.update_attributes({
                  :schedule_id => @schedule.id,
                  :document_id => doc.to_i,
                  :slide_interval_time => value["slide_interval_time"],
                  :play_order => value["play_order"]
              })
            else
              attachment = Attachment.find_by(:document_id => doc.to_i,
                                              :schedule_id => @schedule.id)
              attachment.destroy unless attachment.nil?
            end
          }
        end

        unless params[:schedule][:contents].nil?
          params[:schedule][:contents].each { |content, value|
            if value["enabled"]
              cs = ContentSchedule.find_or_initialize_by(:content_id => content.to_i,
                                                         :schedule_id => @schedule.id)
              
              if value["slide_interval_time"].nil? or !value["slide_interval_time"].match(/^[0-9]+$/)
                flag = false
              end

              if value["play_order"].nil? or !value["play_order"].match(/^[0-9]+$/)
                flag = false
              end

              cs.update_attributes({
                  :schedule_id => @schedule.id,
                  :content_id => content.to_i,
                  :slide_interval_time => value["slide_interval_time"],
                  :play_order => value["play_order"]
              })
            else
              cs = ContentSchedule.find_by(:content_id => content.to_i,
                                           :schedule_id => @schedule.id)
              cs.destroy unless cs.nil?
            end
          }
        end

        if flag
          format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
          format.js { render js: %(window.location.href='#{edit_schedule_path(@schedule)}') }
        else
          format.html { redirect_to edit_schedule_path(@schedule), alert: "Please enter all the required fields (play_order, interval)" }
        end


      else
        format.html { render :edit }
      end
    end
  end

  def show
  	@schedule = Schedule.find_by_id(params[:id])

    @everything = @schedule.get_all_contents_and_attachments if @schedule
    @deployments = @schedule.deployments if @schedule
    @clients = @schedule.clients
    @content_schedules = @schedule.content_schedules.sort_by(&:play_order) if @schedule
    @contents = @schedule.contents if @schedule
    @attachments = @schedule.attachments.sort_by(&:play_order) if @schedule
    @documents = @schedule.documents if @schedule
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @deployments = @schedule.deployments
    @deployments.each do |deployment| 
      deployment.update_attributes(:retries_count => 0)
      DestroyDeploymentJob.perform_later(deployment.id)
    end

    @schedule.update_attributes(:delete_flag => true)
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule stop was successfully initiated, it will take some time to finish ' }
      format.json { head :no_content }
    end
  end

  def add_documents 

  end

  def deploy
    @schedule = Schedule.find(params[:id])
    if @schedule.is_deployable and @schedule.deploy!
      redirect_to schedule_url(@schedule), notice: "Deployment started"
    else
      redirect_to schedule_url(@schedule), notice: "Deployment not started conversion pending"
    end
  end

  private
      # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:description,
                                      :name,
                                      :marquee,
                                      :priority,
                                      :start_hour,
                                      :start_minute,
                                      :end_hour,
                                      :end_minute,
                                      :start_date,
                                      :end_date,
                                      :is_played_on_monday,
                                      :is_played_on_tuesday,
                                      :is_played_on_wednesday,
                                      :is_played_on_thursday,
                                      :is_played_on_friday,
                                      :is_played_on_saturday,
                                      :is_played_on_sunday,
                                      {:client_ids => []},
                                      {:group_ids => []},
                                      {:documents => []},
                                      {:contents => []},
                                      {content_schedules_attributes: [:id,
                                                                      :play_order, 
                                                                      :slide_interval_time, 
                                                                      {:content_attributes => [:id, :file, :description]}
                                                                    ]}
)
    end


end

webapp/app/helpers/schedules_helper.rb
module SchedulesHelper
end

webapp/app/views/schedules/_content_schedule.html.erb
<div class="row">
  <div class="col-md-12">

    <%= builder.fields_for :content_schedules do |csbuilder| %>
      <div class="content-form">
        <% if csbuilder.object.new_record? %>
          <h6>New Content</h6>
        <% end %>
        <div class="row">
          <div class="col-md-12">
            <div class="col-md-3">
              <%= csbuilder.input :priority, label: false, placeholder: "Priority", wrapper: false %>
            </div>
            <div class="col-md-9">
              <div class="row">
                <div class="col-md-4">
                  <%= csbuilder.label :slide_interval_time %>
                </div>
                <div class="col-md-8">
                    <%= csbuilder.input :slide_interval_time, label: false, placeholder: "Slide Interval Time", wrapper: false, input_html: {:min => '4', :value => '4' } %>
                </div>
              </div>
              <div class="row">
                <%= csbuilder.fields_for :content do |cbuilder| %>
                  <%= render 'contents/form_fields', :f => cbuilder %> <!-- todo: for now just content.new -->
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <!-- these two divs are required for content form -->
    <div id="upload-progress">
    </div>
    <div id="uploaded-contents">
    </div>
  </div>
  <div class="col-md-3">
  </div>
</div>

webapp/app/views/schedules/_form.html.erb
<%= simple_form_for @schedule, :validate => true, :class => "form-horizontal", :html => { :multipart => true } do |builder| %>

	<div class="row">
    <%= builder.error_notification %>
    <% if @schedule.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @schedule.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


		<div class="col-md-12">
			<div class="col-md-10">
        <%= builder.input :name, :wrapper => :horizontal_input %>

        <label for="schedule_priority" class="col-md-2 control-label">Priority</label>
        <%= builder.input :priority, :as => :select, :collection => Schedule.priorities.keys.to_a, label: false %>
        <div class="row">
          <div class="form-group">
            <div class="col-md-12">
              <div class="form-group row">
                <label for="inputKey" class="col-md-2 control-label">Start Date</label>
                <div class="col-md-4">
                    <%= builder.date_select :start_date, :start_year => 2015, prompt: true, label: false, wrapper: false %>
                </div>
                <label for="inputValue" class="col-md-2 control-label">End Date</label>
                <div class="col-md-4">
                    <%= builder.date_select :end_date, :start_year => 2015, prompt: true, label: false, wrapper: false %>
                </div>
              </div>

              <div class="form-group row">
                <label for="inputKey" class="col-md-2 control-label">Start Time (day)</label>
                <div class="col-md-4">
                    <%= builder.collection_select :start_hour, Schedule::HOURS, :to_s, :humanize %> : 
                    <%= builder.collection_select :start_minute, Schedule::MINUTES, :to_s, :humanize %>
                </div>
                <label for="inputValue" class="col-md-2 control-label">End Time (day)</label>
                <div class="col-md-4">
                    <%= builder.collection_select :end_hour, Schedule::HOURS, :to_s, :humanize %> : 
                    <%= builder.collection_select :end_minute, Schedule::MINUTES, :to_s, :humanize %>
                </div>
              </div>


            </div>
          </div>
        </div>

        <div class="row">
          <label class="text required col-sm-2 control-label"><abbr title="required">*</abbr> Days of Week</label>
          <div class="col-sm-10">
            <span>
              <% checked = @schedule.is_played_on_monday ? 'checked="checked"' : "" %>
              <input value="0" type="hidden" name="schedule[is_played_on_monday]">
              <label class="boolean optional" for="schedule_is_played_on_monday">
                <input class="boolean optional" type="checkbox" value="1" name="schedule[is_played_on_monday]" 
                <%= checked %> id="schedule_is_played_on_monday">
                Monday
              </label>
            </span>
            <span>
              <% checked = @schedule.is_played_on_tuesday ? 'checked="checked"' : "" %>
              <input value="0" type="hidden" name="schedule[is_played_on_tuesday]">
              <label class="boolean optional" for="schedule_is_played_on_tuesday">
                <input class="boolean optional" type="checkbox" value="1" name="schedule[is_played_on_tuesday]" 
                <%= checked %> id="schedule_is_played_on_tuesday">
                Tuesday
              </label>
            </span>
            <span>
              <% checked = @schedule.is_played_on_wednesday ? 'checked="checked"' : "" %>
              <input value="0" type="hidden" name="schedule[is_played_on_wednesday]">
              <label class="boolean optional" for="schedule_is_played_on_wednesday">
                <input class="boolean optional" type="checkbox" value="1" name="schedule[is_played_on_wednesday]" 
                <%= checked %> id="schedule_is_played_on_wednesday">
                Wednesday
              </label>
            </span>
            <span>
              <% checked = @schedule.is_played_on_thursday ? 'checked="checked"' : "" %>
              <input value="0" type="hidden" name="schedule[is_played_on_thursday]">
              <label class="boolean optional" for="schedule_is_played_on_thursday">
                <input class="boolean optional" type="checkbox" value="1" name="schedule[is_played_on_thursday]" 
                <%= checked %> id="schedule_is_played_on_thursday">
                Thursday
              </label>
            </span>
            <span>
              <% checked = @schedule.is_played_on_friday ? 'checked="checked"' : "" %>
              <input value="0" type="hidden" name="schedule[is_played_on_friday]">
              <label class="boolean optional" for="schedule_is_played_on_friday">
                <input class="boolean optional" type="checkbox" value="1" name="schedule[is_played_on_friday]" 
                <%= checked %> id="schedule_is_played_on_friday">
                Friday
              </label>
            </span>
            <span>
              <% checked = @schedule.is_played_on_saturday ? 'checked="checked"' : "" %>
              <input value="0" type="hidden" name="schedule[is_played_on_saturday]">
              <label class="boolean optional" for="schedule_is_played_on_saturday">
                <input class="boolean optional" type="checkbox" value="1" name="schedule[is_played_on_saturday]" 
                <%= checked %> id="schedule_is_played_on_saturday">
                Saturday
              </label>
            </span>
            <span>
              <% checked = @schedule.is_played_on_sunday ? 'checked="checked"' : "" %>
              <input value="0" type="hidden" name="schedule[is_played_on_sunday]">
              <label class="boolean optional" for="schedule_is_played_on_sunday">
                <input class="boolean optional" type="checkbox" value="1" name="schedule[is_played_on_sunday]" 
                <%= checked %> id="schedule_is_played_on_sunday">
                Sunday
              </label>
            </span>
          </div>
        </div>

				<%= builder.input :description, :placeholder => "Description", :rows => "2", :wrapper => :horizontal_input %>
        <%= builder.input :marquee, :placeholder => "Marquee Text", :wrapper => :horizontal_input, input_html: {rows: '9'} %>
			</div>

			<div class="col-md-2">
        <div class="row">
  				<%= builder.button :submit, :class => "btn btn-large btn-primary btn-block", :style => "display: inline" %>
        </span>
        <% unless @schedule.new_record? %>
          <span class="row">      
            <%= link_to "Add Document", new_schedule_attachment_path(@schedule), :class => "btn btn-primary btn-block" %>
          </span>
          <span class="row">
            <%= link_to "Add Media", new_schedule_content_schedule_path(@schedule), :class => "btn btn-primary btn-block" %>
          </span>
        <% end %>

			</div>
		</div>
	</div>

  <% unless @schedule.new_record? %>

    <div class="row">
      <h6> Contents </h6>
    </div>
    

    <div class="col-sm-12">
      <% if @everything.any? %>

        <div class="row">
          <table class="table table-condensed table-bordered">
            <thead>
              <tr>
                <th>Type</th>
                <th>Play Order</th>
                <th>Slide Interval</th>
                <th>Description</th>
                <th>Thumbnail</th>
                <th>Converted?</th>
                <th colspan=2>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @everything.each do |obj| %>
                <tr>
                  <% if obj.class.name == "Attachment" %>
                    <td><strong>Document</strong></td>
                    <td>
                      <%= link_to "UP", attachment_up_play_order_path(@schedule, obj), :method => :post, class: "btn btn-primary btn-xs" %>
                      <br />
                      <strong><%= obj.play_order %></strong>
                      <br />
                      <%= link_to "DOWN", attachment_down_play_order_path(@schedule, obj), :method => :post, class: "btn btn-primary btn-xs" %>
                    </td>
                  <% else %>
                    <td><strong>Media</strong></td>
                    <td>
                      <%= link_to "UP", content_schedule_up_play_order_path(@schedule, obj), :method => :post, class: "btn btn-primary btn-xs" %>
                      <br />
                      <strong><%= obj.play_order %></strong>
                      <br />
                      <%= link_to "DOWN", content_schedule_down_play_order_path(@schedule, obj), :method => :post, class: "btn btn-primary btn-xs" %>
                    </td>
                  <% end %>
                  <td><%= obj.slide_interval_time %></td>
                  <% if obj.class.name == "Attachment" %>
                    <td><%= obj.document.description %></td>
                    <td>
                      <% unless obj.document.images.count == 0 %>
                        <%= image_tag obj.document.images.first.file_url(:thumb).to_s %>
                      <% end %>
                    </td>
                    <td><%= obj.is_converted %></td>
                    <td><%= link_to "Edit", edit_schedule_attachment_path(@schedule, obj), :class => "btn btn-primary" %></td>
                    <td><%= link_to "Delete", schedule_attachment_path(@schedule, obj), :method => :delete, :class => "btn btn-danger" %></td>
                  <% else %>
                    <td><%= obj.content.description %></td>
                    <td><%= image_tag obj.content.file_url(:thumb).to_s %></td>
                    <td><%= obj.is_converted %></td>
                    <td><%= link_to "Edit", edit_schedule_content_schedule_path(@schedule, obj), :class => "btn btn-primary" %></td>
                    <td><%= link_to "Delete", schedule_content_schedule_path(@schedule, obj), :method => :delete, :class => "btn btn-danger" %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

    <div class="row">
      <br />
      <br />
      <h6>Deploy to</h6>
      <div id="clients_table" class="col-sm-12">

        <div class="field">
          <p><strong>Clients</strong></p>
          <%= hidden_field_tag("schedule[client_ids][]", nil) %>
          <table class="table table-condensed">
            <tr>
              <th></th>
              <th>IP Address </th>
              <th>Name </th>
              <th>Department </th>
              <th>Building </th>
              <th>Floor </th>
            </tr>
            <% Client.all.each do |client| %>
            <% id = client.id %>
            <tr>
              <td><%= check_box_tag("schedule[client_ids][]", id, id.in?(@clients.collect(&:id))) %></td> 
              <td><%= client[:ip_address] %></td>
              <td><%= client[:name] %></td>
              <td><%= client[:department] %></td>
              <td><%= client[:building] %></td>
              <td><%= client[:floor] %></td>

            </tr>
            <% end %>
          </table>
        </div>

      </div>
    </div>

  <% end %>

<% end %>

webapp/app/views/schedules/edit.html.erb
<h6>Edit Schedule</h6>
<br />

<%= render 'form' %>

webapp/app/views/schedules/index.html.erb
<h6>Schedules</h6>
<br/>

<table class="table table-condensed">
	<thead>
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>Description</th>
		<th># of Clients</th>
		<th>Total Running Time</th>
		<th>Status</th>
		<th colspan="3"></th>
	</tr>
	</thead>

	<tbody>
	<% id = 0 %>
	<% @schedules.each do |s| %>
		<% id = 1 + id %>
		<tr>
			<td><%= id %></td>
			<td><%= link_to s[:name], schedule_path(s) %></td>
			<td><%= link_to (truncate(s[:description], length: 20)), schedule_path(s) %></td>
			<td><%= s.all_clients.size %></td>
			<td><%= s[:total_running_time] %></td>
			<td><%= s[:status] %></td>
			<td><%= link_to "Show", schedule_path(s), class: "btn btn-mini btn-primary" %></td>
			<td><%= link_to "Edit", edit_schedule_path(s), class: "btn btn-mini btn-primary" %></td>
			<% if not s.delete_flag %>
				<td><%= link_to "Stop", s, :method => :delete, data: {:confirm => "Are you sure"}, :class => "btn btn-mini btn-danger" %></td>
			<% end %>

		</tr>
	<% end %>
	</tbody>
</table>

webapp/app/views/schedules/new.html.erb
<h6>Create a New Schedule</h6>
<p><strong>Step 1:</strong> Insert the basic information associated to the schedule</p>
<p><strong>Step 2:</strong> Click Create Schedule</p>
<p><strong>Step 3:</strong> Edit information or add contents</p>

<br/>

<%= render 'form' %>