webapp/config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do


  resources :marquees

  mount Sidekiq::Web => '/sidekiq'

  resources :users
  resources :contents
  resources :documents
  resources :images
  resources :groups
  resources :schedules do 
    resources :deployments, only: [:index]
    resources :content_schedules
    resources :attachments
  end

  post 'schedules/:schedule_id/attachments/:id/up_play_order' => 'attachments#up_play_order', :as => :attachment_up_play_order
  post 'schedules/:schedule_id/attachments/:id/down_play_order' => 'attachments#down_play_order', :as => :attachment_down_play_order

  post 'schedules/:schedule_id/content_schedules/:id/up_play_order' => 'content_schedules#up_play_order', :as => :content_schedule_up_play_order
  post 'schedules/:schedule_id/content_schedules/:id/down_play_order' => 'content_schedules#down_play_order', :as => :content_schedule_down_play_order

  post 'schedules/:id/deploy' => 'schedules#deploy', :as => :deploy_schedule
  post 'marquees/:id/push' => 'marquees#push', :as => :push_marquee


  get 'dashboard/clients', :as => :clients_status
  get 'dashboard/schedules', :as => :schedules_status

  get 'sessions/new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  resources :users
  resources :clients


  # You can have the root of your site routed with "root"
  root 'dashboard#clients'

end

webapp/app/models/group.rb
class Group < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :clients
  #has_and_belongs_to_many :schedules

end

webapp/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password, :password_confirmation


  before_save :encrypt_password

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_uniqueness_of :email

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :password, :on => :update

  has_many :clients
  has_many :groups

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end



end

webapp/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_filter :authenticate
  before_action :set_group, only: [:update, :destroy]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find_by_id(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end


  def edit
    @group = Group.find_by_id(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name,
                                    {client_ids: []},
                                    :description,
                                    :building,
                                    :college,
                                    :department,
                                    :group_size,
                                    :contact_info)
    end

end

webapp/app/helpers/groups_helper.rb
module GroupsHelper
end

webapp/app/views/groups/_form.html.erb
<!-- Groups Form -->

<%= simple_form_for @group, :html => {:class => "form-horizontal col-md-8"} do |f| %>

  <%= f.error_notification %>
  <% if @group.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <%= f.input :name, :wrapper => :horizontal_input %>
  <%= f.input :description, :wrapper => :horizontal_input %>
  <%= f.input :building, :wrapper => :horizontal_input %>
  <%= f.input :college, :wrapper => :horizontal_input %>
  <%= f.input :department, :wrapper => :horizontal_input %>
  <%= f.input :group_size, :wrapper => :horizontal_input %>
  <%= f.input :contact_info, :wrapper => :horizontal_input %>

  <div class="field">
    <p><strong>Clients</strong></p>
    <%= hidden_field_tag("client[group_ids][]", nil) %>
    <table class="table table-condensed">
      <tr>
        <th></th>
        <th>IP Address </th>
        <th>Name</th>
        <th>Department </th>
        <th>Building </th>
        <th>Floor </th>
      </tr>
      <% Client.all.each do |client| %>
      <% id = client.id %>
      <tr>
        <td><%= check_box_tag("group[client_ids][]", id, id.in?(@group.clients.collect(&:id))) %></td> 
        <td><%= client[:ip_address] %></td>
        <td><%= client[:name] %></td>
        <td><%= client[:department] %></td>
        <td><%= client[:building] %></td>
        <td><%= client[:floor] %></td>

      </tr>
      <% end %>
    </table>
  </div>

  <%= f.button :submit %>
<% end %>

webapp/app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

webapp/app/views/groups/delete.html.erb
<h1>Groups#delete</h1>
<p>Find me in app/views/groups/delete.html.erb</p>

webapp/app/views/groups/edit.html.erb
<h6>Editing Group</h6>
<br />

<%= render 'form' %>

webapp/app/views/groups/index.html.erb
<h6>Listing Groups</h6>
<br/>


<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>College</th>
      <th>Department</th>
      <th>Building</th>
      <th>Group Size</th>
      <th>Contact Info</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= group.description %></td>
        <td><%= group.college %></td>
        <td><%= group.department %></td>
        <td><%= group.building %></td>
        <td><%= group.group_size %></td>
        <td><%= group.contact_info %></td>
        <td><%= link_to 'Edit', edit_group_path(group), :class => "btn btn-mini btn-primary" %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

webapp/app/views/groups/new.html.erb
<h6>New Group</h6>
<br />
<br />

<%= render 'form' %>

webapp/app/views/groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Building:</strong>
  <%= @group.building %>
</p>

<p>
  <strong>College:</strong>
  <%= @group.college %>
</p>

<p>
  <strong>Department:</strong>
  <%= @group.department %>
</p>

<p>
  <strong>Group_size:</strong>
  <%= @group.group_size %>
</p>

<p>
  <strong>Contact info:</strong>
  <%= @group.contact_info %>
</p>


<br />
<p><strong>Clients </strong></p>

<table class="table table-condensed">
  <tr>
    <th>#</th>
    <th>IP Address </th>
    <th>Department </th>
    <th>Building </th>
    <th>Floor </th>
  </tr>
  <% id = 0 %>
  <% Client.all.each do |client| %>
  <% id = 1+id %>
  <tr>
    <td><%= id %></td>
    <td><%= client[:ip_address] %></td>
    <td><%= client[:department] %></td>
    <td><%= client[:building] %></td>
    <td><%= client[:floor] %></td>
  </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

webapp/app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>