webapp/config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do


  resources :marquees

  mount Sidekiq::Web => '/sidekiq'

  resources :users
  resources :contents
  resources :documents
  resources :images
  resources :groups
  resources :schedules do 
    resources :deployments, only: [:index]
    resources :content_schedules
    resources :attachments
  end

  post 'schedules/:schedule_id/attachments/:id/up_play_order' => 'attachments#up_play_order', :as => :attachment_up_play_order
  post 'schedules/:schedule_id/attachments/:id/down_play_order' => 'attachments#down_play_order', :as => :attachment_down_play_order

  post 'schedules/:schedule_id/content_schedules/:id/up_play_order' => 'content_schedules#up_play_order', :as => :content_schedule_up_play_order
  post 'schedules/:schedule_id/content_schedules/:id/down_play_order' => 'content_schedules#down_play_order', :as => :content_schedule_down_play_order

  post 'schedules/:id/deploy' => 'schedules#deploy', :as => :deploy_schedule
  post 'marquees/:id/push' => 'marquees#push', :as => :push_marquee


  get 'dashboard/clients', :as => :clients_status
  get 'dashboard/schedules', :as => :schedules_status

  get 'sessions/new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  resources :users
  resources :clients


  # You can have the root of your site routed with "root"
  root 'dashboard#clients'

end

webapp/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password, :password_confirmation


  before_save :encrypt_password

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_uniqueness_of :email

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :password, :on => :update

  has_many :clients
  has_many :groups

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end



end

webapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if current_user.is_admin? && @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def edit

  end

  def update
    respond_to do |format|
      if current_user.is_admin? && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully udpated' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if current_user.is_admin? && !@user.is_admin? && @user.destroy
        format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
      else
        format.html { redirect_to users_url, notice: 'An error occurred while deleting the users.' }
      end
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

end

webapp/app/helpers/users_helper.rb
module UsersHelper
end

webapp/app/views/users/_form.html.erb
<!-- User form -->

<%= simple_form_for @user, :html => {:class => "form-horizontal col-md-8"} do |f| %>

  <%= f.error_notification %>
  <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>


  <%= f.input :first_name, :wrapper => :horizontal_input %>
  <%= f.input :last_name, :wrapper => :horizontal_input %>
  <%= f.input :email, :wrapper => :horizontal_input %>
  <%= f.input :password, :wrapper => :horizontal_input %>
  <%= f.input :password_confirmation, :wrapper => :horizontal_input %>

  <%= f.button :submit %>
<% end %>

webapp/app/views/users/edit.html.erb
<h2>Edit User</h2>
<br />
<br />

<%= render "form" %>

webapp/app/views/users/index.html.erb
<h6>Listing Users</h6>
<br/>


<table class="table table-condensed">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.first_name, user_path(user) %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to 'Edit', edit_user_path(user), :class => "btn btn-mini btn-primary" %></td>
        <% unless user.is_admin? %>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

webapp/app/views/users/new.html.erb
<h3>New User</h3>
<br />
<br />

<%= render "form" %>

webapp/app/views/users/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email Name:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-mini btn-primary" %> |
<%= link_to 'Back', users_path, :class => "btn btn-mini btn-primary" %>